### ISSUE TITLE
Exception causing crash

### ISSUE THREAD

**Issue by xkforce** [Axieum/JER-Ore-Integration#1]
https://paste.ee/p/uoyYd

**Comment by axieum** [comment]
Can I please ask if you have disabled any biomes from the `Biomes O' Plenty` mod? It appears from the log you supplied, that the `Eucalyptus Forest` is not in the game, or has not been loaded yet by `Biomes O' Plenty`.

**Comment by xkforce** [comment]
Some biomes were indeed disabled by setting their biome ids to -1 in the biome_ids.json file.  If any of them are disabled, JER ore integration crashes.  I've tried to disable certain biomes in other ways but setting the biome ids to -1 is the only method that I know of.

**Comment by axieum** [comment]
This helps a bunch, I have spent a while, and am currently working on removing as much `hardcoded` parts as possible; adding the ability to create any `example.json` files in the config folder to have it load the ores from it - but will be populated with default values to begin with for the convenience of `plug n play`.
