### ISSUE TITLE
No example file

### ISSUE THREAD

**Issue by ghost** [Axieum/JER-Ore-Integration#2]
Hi, If we dont use Biomes O'Plenty then no example.json file is created. So could you please have an example file included in the config folder?

**Comment by Spaig** [comment]
Seconding this request!

**Comment by ghost** [comment]
if you use /profile 100 all, JER will produce a config file with all ore gen within 100 chunks in all dimensions

**Comment by Spaig** [comment]
Didn't work for me :(

**Comment by ghost** [comment]
if you have tickprofiler installed you'll have to edit TickProfiler.cfg config file and change command name because its same as JER Resource.

It should produce a file in the JustEnoughResources config folder

**Comment by way2muchnoise** [comment]
In the most recent version I have changed the name of the command to /jer_profile to prevent this command name conflict
